### ISSUE TITLE
The setting of Sample Rates does not check if user enters number > 7

### ISSUE THREAD

**Issue by Gerriko** [FemmeVerbeek/Arduino_LSM9DS1#6]
`int LSM9DS1Class::setAccelODR(int8_t range) //Sample Rate 0:off, 1:10Hz, 2:50Hz, 3:119Hz, 4:238Hz, 5:476Hz, 6:952Hz, 7:NA
{  if (range==7) range =0; 
   range = (range & 0b00000111) << 5;
   uint8_t setting = ((readRegister(LSM9DS1_ADDRESS, LSM9DS1_CTRL_REG6_XL) & 0b00011111) | range);
   return writeRegister(LSM9DS1_ADDRESS, LSM9DS1_CTRL_REG6_XL,setting) ;
}`

It would be very easy to forget that the sample rate settings are 0 to 6. One could easily enter 10 (as in 10Hz) instead of 1. In this case you have no check that the range value entered, i.e. 10 is greater than 6.

Also would it not be better to use uint8 instead for range to prevent negative values entered too.

**Comment by FemmeVerbeek** [comment]
The function did check this, but the outcome could still be 7 when the entered numbers are 15, 23,31. Probably no harm as all I wanted to avoid is the NA. setting
Bitwise there is no difference between uint8_t and int8_t. 
Fixed both
